[package]
name = "passivetool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
surf = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
colored = "2.0"
